"""Tidyra — Flet application entry point."""

from __future__ import annotations

import flet as ft

from tidyra.application.services import OrganizeService
from tidyra.infrastructure.filesystem import LocalFileSystem
from tidyra.infrastructure.logging import configure_logging, logger
from tidyra.presentation.brand import icon_path
from tidyra.presentation.controller import TidyraApp
from tidyra.presentation.state import UIState


async def main(page: ft.Page) -> None:
    """Flet async entry point. Invoked by ``uv run tidyra``."""
    page.title = "Tidyra"
    page.theme_mode = ft.ThemeMode.SYSTEM
    page.padding = 0
    page.window.width = 760
    page.window.height = 640

    # Brand the window. Flet 0.86 on Windows only honours ``.ico`` — SVG
    # is silently ignored. The ICO is a procedural export of the brand
    # mark, generated by ``tools/build_icon.py`` and shipped via
    # ``presentation/brand.icon_path()``.
    page.window.icon = str(icon_path())

    # Glassmorphism scrollbar — translucent thumb, near-invisible track,
    # always visible so the user can see (and grab) the scroll position
    # without having to hover first. Uses ``ON_SURFACE`` so it adapts to
    # light/dark mode automatically.
    page.theme = ft.Theme(
        scrollbar_theme=ft.ScrollbarTheme(
            thumb_color=ft.Colors.with_opacity(0.45, ft.Colors.ON_SURFACE),
            track_color=ft.Colors.with_opacity(0.04, ft.Colors.ON_SURFACE),
            track_border_color=ft.Colors.TRANSPARENT,
            thickness=10,
            radius=8,
            main_axis_margin=4,
            cross_axis_margin=2,
            min_thumb_length=36,
            thumb_visibility=True,
            track_visibility=False,
        ),
    )

    service = OrganizeService(LocalFileSystem())
    state = UIState(service=service)
    app = TidyraApp(page=page, state=state)
    state.on_navigate = app.render

    picker = ft.FilePicker()
    # Flet 0.86: services live on ``page.services``, not ``page.overlay``.
    # Adding a service to the overlay renders an "Unknown control" stub
    # and the client never wires up the invoke-method listener, which
    # causes every ``get_directory_path`` call to time out after 10 s.
    page.services.append(picker)
    app.picker = picker

    logger.bind(component="presentation", screen="home").info("tidyra app started")
    app.render()


def run() -> None:
    """Console-script entry point — wraps ``main`` with ``ft.run``.

    Initialises logging before Flet takes over so import-time failures
    (broken TOML, missing resources, etc.) still surface in the sinks.
    """
    configure_logging()
    ft.run(main)
