"""Procedurally generate the Tidyra brand-asset set from the brand source.

Why this script exists
----------------------

Tidyra ships binaries for Windows, macOS, and Linux. Each platform needs
a different icon format:

- Windows  : ``.ico`` containing one or more PNG payloads (Vista+).
- macOS    : an ``.icns`` file (typically produced by ``iconutil`` from
             a multi-size ``.iconset`` directory of PNGs).
- Linux    : a single PNG (typically 256x256 or 512x512).

The brand source is ``src/tidyra/resources/tidyra-logo.svg``. We do not
want to take Pillow / cairosvg / pyvips just to rasterize, so this
script generates the full icon set using **stdlib only** (``zlib`` +
``struct``).

Outputs (relative to repo root)::

    assets/icons/tidyra-icon.ico       — Windows build icon + page.window.icon
    assets/icons/icon.png              — Linux build icon (256x256)
    assets/icons/png/tidyra-icon-16.png
    assets/icons/png/tidyra-icon-32.png
    assets/icons/png/tidyra-icon-48.png
    assets/icons/png/tidyra-icon-64.png
    assets/icons/png/tidyra-icon-128.png
    assets/icons/png/tidyra-icon-256.png
    assets/icons/png/tidyra-icon-512.png
    assets/icons/png/tidyra-icon-1024.png

The macOS ``.icns`` is generated by the GitHub Actions release
workflow (``iconutil`` is macOS-only) — see
``docs/plans/2026-09-02--cross-platform-packaging.md``.

Usage::

    uv run python tools/build_icon.py

Regenerate whenever the brand palette or proportions change. The script
is deterministic — same SVG implies same icons.
"""

from __future__ import annotations

import struct
import zlib
from collections.abc import Iterable
from pathlib import Path

# Brand palette (matches ``src/tidyra/resources/tidyra-logo.svg``).
_FOLDER_BODY = (0x0F, 0x76, 0x6E, 0xFF)  # deep teal #0F766E
_FILE_CARD = (0x5E, 0xEA, 0xD4, 0xFF)  # light teal #5EEAD4
_FILE_CARD_ALT = (0x5E, 0xEA, 0xD4, 0xC0)  # 75% alpha
_FILE_CARD_ALT2 = (0x5E, 0xEA, 0xD4, 0x80)  # 50% alpha
_TRANSPARENT = (0, 0, 0, 0)

# Brand geometry is authored on a 32-unit grid; the renderer scales
# every coordinate by ``size / 32`` to land on integer pixel boundaries.
_REFERENCE = 32

# Each rect: (x0, y0, x1, y1, color) on the 32-unit grid.
_RECTS = (
    (4, 7, 13, 12, _FOLDER_BODY),  # Folder tab
    (3, 11, 29, 27, _FOLDER_BODY),  # Folder body outer
    (4, 12, 28, 26, _FOLDER_BODY),  # Folder body inner (rounded approximation)
    (6, 15, 26, 18, _FILE_CARD),  # File bar 1
    (6, 19, 22, 22, _FILE_CARD_ALT),  # File bar 2
    (6, 23, 24, 26, _FILE_CARD_ALT2),  # File bar 3
)

# Pixels in the four corners (on the 32-unit grid) are forced to
# transparent so the icon does not look like a tinted square at small
# sizes (where the corner-to-corner gap is too thin to read).
_CORNER_PIXELS: tuple[tuple[int, int], ...] = (
    (0, 0),
    (1, 0),
    (0, 1),
    (30, 0),
    (31, 0),
    (31, 1),
    (0, 30),
    (1, 31),
    (0, 31),
    (30, 31),
    (31, 30),
    (31, 31),
)

# PNG sizes to generate. These cover Linux (256 is canonical), the
# macOS .iconset format (16, 32, 64, 128, 256, 512, 1024 at 1x and 2x),
# and every sensible Windows .ico size.
PNG_SIZES: tuple[int, ...] = (16, 32, 48, 64, 128, 256, 512, 1024)


def _scale(v: int, size: int) -> int:
    """Map a 32-unit-grid coordinate to a ``size``-pixel grid.

    Rounds to nearest, with the constraint that rects never collapse
    below 1 px wide. The clipping in :func:`_render_brand` keeps us
    inside the buffer; this just gives us an integer pixel index.
    """
    return max(0, min(size, round(v * size / _REFERENCE)))


def _blit(
    buf: bytearray,
    width: int,
    height: int,
    x0: int,
    y0: int,
    x1: int,
    y1: int,
    color: tuple[int, int, int, int],
) -> None:
    """Draw a filled rect (exclusive end coords) into an RGBA pixel buffer."""
    for y in range(max(0, y0), min(height, y1)):
        for x in range(max(0, x0), min(width, x1)):
            idx = (y * width + x) * 4
            buf[idx : idx + 4] = bytes(color)


def render_brand(size: int) -> bytes:
    """Render the brand mark into an RGBA pixel buffer of side ``size``."""
    buf = bytearray(b"\x00" * (size * size * 4))
    for x0, y0, x1, y1, color in _RECTS:
        _blit(
            buf,
            size,
            size,
            _scale(x0, size),
            _scale(y0, size),
            _scale(x1, size),
            _scale(y1, size),
            color,
        )
    # Force corner pixels to transparent so the icon reads as a folder
    # shape, not a tinted square. Skip at sizes < 32 (the corners don't
    # have space to clear).
    if size >= _REFERENCE:
        for x, y in _CORNER_PIXELS:
            sx, sy = _scale(x, size), _scale(y, size)
            if 0 <= sx < size and 0 <= sy < size:
                idx = (sy * size + sx) * 4
                buf[idx : idx + 4] = bytes(_TRANSPARENT)
    return bytes(buf)


def _png_chunk(tag: bytes, data: bytes) -> bytes:
    """One PNG chunk: length + type + payload + CRC32."""
    body = tag + data
    crc = zlib.crc32(body) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + body + struct.pack(">I", crc)


def make_png(width: int, height: int, rgba: bytes) -> bytes:
    """Encode an RGBA pixel buffer as a minimal PNG."""
    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(
        ">IIBBBBB",
        width,
        height,
        8,  # bit depth
        6,  # color type: RGBA
        0,  # compression
        0,  # filter
        0,  # interlace
    )
    raw = b"".join(b"\x00" + rgba[y * width * 4 : (y + 1) * width * 4] for y in range(height))
    idat = zlib.compress(raw, 9)
    return sig + _png_chunk(b"IHDR", ihdr) + _png_chunk(b"IDAT", idat) + _png_chunk(b"IEND", b"")


def make_ico(width: int, height: int, png: bytes) -> bytes:
    """Wrap a single PNG payload in an ICO container (Vista+ supported)."""
    header = struct.pack("<HHH", 0, 1, 1)
    entry = struct.pack(
        "<BBBBHHII",
        width if width < 256 else 0,
        height if height < 256 else 0,
        0,
        0,  # color_count, reserved
        1,
        32,  # planes, bit_count
        len(png),
        6 + 16,  # offset = header + entry
    )
    return header + entry + png


def _ensure(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def write_png_set(png_dir: Path, sizes: Iterable[int] = PNG_SIZES) -> list[Path]:
    """Render and write the multi-size PNG set. Returns the written paths."""
    written: list[Path] = []
    for size in sizes:
        rgba = render_brand(size)
        png = make_png(size, size, rgba)
        target = png_dir / f"tidyra-icon-{size}.png"
        _ensure(target)
        target.write_bytes(png)
        written.append(target)
    return written


def write_ico(ico_path: Path, size: int = 256) -> Path:
    """Render and write a single-size ``.ico``. Default size: 256x256."""
    rgba = render_brand(size)
    png = make_png(size, size, rgba)
    ico = make_ico(size, size, png)
    _ensure(ico_path)
    ico_path.write_bytes(ico)
    return ico_path


def write_linux_icon(linux_icon_path: Path, size: int = 256) -> Path:
    """Render and write the canonical Linux build icon (single PNG)."""
    rgba = render_brand(size)
    png = make_png(size, size, rgba)
    _ensure(linux_icon_path)
    linux_icon_path.write_bytes(png)
    return linux_icon_path


def build_all(repo_root: Path | None = None) -> dict[str, list[Path]]:
    """Build the full icon set. Returns a mapping of what was written.

    Two ICOs are produced:

    - ``assets/icons/tidyra-icon.ico`` is consumed by ``flet build`` to
      brand the Windows executable.
    - ``src/tidyra/resources/tidyra-icon.ico`` is packaged with the
      wheel and read at runtime by ``presentation.brand.icon_path()``
      for ``page.window.icon``.

    Both are byte-identical regenerations from the same brand source.
    """
    root = repo_root or Path(__file__).resolve().parent.parent
    icons = root / "assets" / "icons"
    png_dir = icons / "png"
    runtime_ico = root / "src" / "tidyra" / "resources" / "tidyra-icon.ico"
    return {
        "ico": [write_ico(icons / "tidyra-icon.ico"), write_ico(runtime_ico)],
        "linux": [write_linux_icon(icons / "icon.png")],
        "png_set": write_png_set(png_dir),
    }


if __name__ == "__main__":
    summary = build_all()
    for kind, paths in summary.items():
        for p in paths:
            print(f"  {kind:8s} {p.relative_to(Path.cwd())}  ({p.stat().st_size} bytes)")
    print(f"Built {sum(len(v) for v in summary.values())} assets.")
